## Task

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

### Input Format (1 2 3 4 -8 -10)

A single line of input containing space separated numbers.

### Output Format

Print the reverse NumPy array with type float.

In [6]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    ar = numpy.array(arr, dtype=float)
    return numpy.flip(ar)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]


## Task

You are given a space separated list of nine integers. Your task is to convert this list into a
X

NumPy array.

### Input Format

A single line of input containing

space separated integers.

### Output Format

Print the
X

NumPy array.

### Sample Input

1 2 3 4 5 6 7 8 9

### Sample Output

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
import numpy

list = input().strip().split(" ")

arr = numpy.array(list, dtype=int)

print(numpy.reshape(arr,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Task

You are given a X integer array matrix with space separated elements 
( = rows and columns).
Your task is to print the transpose and flatten results.

### Input Format

The first line contains the space separated values of rows and columns
The next lines contains the space separated elements of rows.

### Output Format

First, print the transpose array and then print the flatten.

### Sample Input

2 2
1 2
3 4

### Sample Output

[[1 3]
 [2 4]]
[1 2 3 4]


In [11]:
import numpy


list = input().strip().split(" ")
n = int(list[0])
m = int(list[1])
values = []
for i in range(n):
    values.append(input().split(" "))
    
arr = numpy.array(values, dtype=int)

print(numpy.reshape(arr,(n,m)).transpose())
print(arr.flatten())

[[1 3]
 [2 4]]
[1 2 3 4]


## Task

You are given two integer arrays of size NxP and MxP (N & M are rows, and P is the column). 
Your task is to concatenate the arrays along axis 0.

### Input Format

The first line contains space separated integers N, M and P.
The next N lines contains the space separated elements of the P columns.
After that, the next M lines contains the space separated elements of the P columns.

### Output Format

Print the concatenated array of size (N+M)xP.

### Sample Input

4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 

### Sample Output

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 


In [ ]:
import numpy 

list = input().strip().split(" ")
n = int(list[0])
m = int(list[1])
p = int(list[2])

values1 = []
for i in range(n):
    values1.append(input().split(" "))

values2 = []
for i in range(m):
    values2.append(input().split(" "))

arr1 = numpy.array(values1, dtype=int)
arr2 = numpy.array(values2, dtype=int)
print(numpy.concatenate((arr1, arr2), axis = 0))
#print(numpy.reshape(arr1,(p,m)))
#print(numpy.reshape(arr2,(p,n)))


[['1', '2'], ['1', '2'], ['1', '2'], ['1', '2']]
[['3', '4'], ['3', '4'], ['3', '4']]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Task

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

### Input Format

A single line containing the space-separated integers.

### Constraints

1 <= each integer <= 3

### Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

### Sample Input 0

3 3 3

### Sample Output 0

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]



In [ ]:
import numpy

list = input().strip().split(" ")

#Pour gérer la taille variable (3 3 3) ou (2 3), il faut utiliser un tuple qui va reprendre en int les valeurs passées en input
liste1 = tuple([int(x) for x in list])

arr = numpy.zeros((liste1), dtype=int)
print(arr)

arr = numpy.ones((liste1), dtype=int)
print(arr)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Task

Your task is to print an array of size NxM
with its main diagonal elements as 1's and
0's everywhere else.

### Note

In order to get alignment correct, please insert the line
numpy.set_printoptions(legacy='1.13')
below the numpy import.

### Input Format

A single line containing the space separated values of N
and M.
N denotes the rows.

M denotes the columns.

### Output Format

Print the desired NxM array.

### Sample Input

3 3

### Sample Output

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [35]:
import numpy

numpy.set_printoptions(legacy='1.13')

list = input().strip().split(" ")

n = int(list[0])
m = int(list[1])

print(numpy.eye(n,m))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


## Task

You are given two integer arrays, A and B of dimensions NxM
Your task is to perform the following operations:

Add (A+B)
Subtract (A-B)
Multiply (A*B)
Integer Division (A/B)
Mod (A%B)
Power (A**B)

Note
There is a method numpy.floor_divide() that works like numpy.divide() except it performs a floor division.

### Input Format

The first line contains two space separated integers, N and M.
The next N lines contains M space separated integers of array A.
The following N lines contains M space separated integers of array B.

### Output Format

Print the result of each operation in the given order under Task.

### Sample Input

1 4
1 2 3 4
5 6 7 8

### Sample Output

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]] 


In [41]:
import numpy

list = input().strip().split(" ")

n = int(list[0])
m = int(list[1])

values=[]
for i in range(n):
    values +=input().split(" ")

a = numpy.array(values, dtype="int")

values=[]
for i in range(n):
    values +=input().split(" ")
b = numpy.array(values, dtype="int")

a = numpy.reshape(a, (n, m))
b = numpy.reshape(b, (n, m))

print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(numpy.floor_divide(a, b))
print(numpy.mod(a, b))
print(numpy.power(a, b))

[[ 6  8 10 12]
 [ 6  8 10 12]]
[[-4 -4 -4 -4]
 [-4 -4 -4 -4]]
[[ 5 12 21 32]
 [ 5 12 21 32]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [1 2 3 4]]
[[    1    64  2187 65536]
 [    1    64  2187 65536]]


## Task
You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.

### Input Format

A single line of input containing the space separated elements of array A.

### Output Format

On the first line, print the floor of A.
On the second line, print the ceil of A.
On the third line, print the rint of A.

#### Sample Input

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9

### Sample Output

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [47]:
import numpy

numpy.set_printoptions(legacy='1.13')

list = input().strip().split(" ")

arr = numpy.array(list, dtype=float)

print(numpy.floor(arr)) 
print(numpy.ceil(arr)) 
print(numpy.rint(arr)) 


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Task

You are given a 2-D array with dimensions NxM.
Your task is to perform the sum tool over axis and then find the product
of that result.

### Input Format

The first line of input contains space separated values of N and M.
The next N lines contains M space separated integers.

### Output Format

Compute the sum along axis 0. Then, print the product of that sum.

### Sample Input

2 2
1 2
3 4

### Sample Output

24

### Explanation

The sum along axis 0 = [4 6]
The product of this sum = 24

In [ ]:
import numpy

list = input().strip().split(" ")
n = int(list[0])
m = int(list[1])
        
values = []
for i in range(n):
    values += input().split(" ")

arr = numpy.array(values, dtype=int)
arr = numpy.reshape(arr, (n,m))
arr0 = numpy.sum(arr, axis=0)
print(numpy.prod(arr0))

[[1 2]
 [3 2]]
[4 4]
16
